Introduction to Climate Ensembles and  Natural Variability
henrifnk/Seminar_ClimateNStatistics pull request #17
Opened 2024-07-16 15:48 UTC by senntaa

Fertiger Bericht

2024-07-17 12:15 UTC, henrifnk requested changes
Bitte aktuelles bib file mit deinen referenzen ergänzen
Die kleinen anmerkungen im Code ausbessern.

2024-07-17 12:15 UTC, henrifnk commented on 01-variability.Rmd
> +```{r Ensemble, cache=FALSE, out.width="500", fig.align="center", echo = FALSE, eval = TRUE}
bitte in allen chunks den namen anfügen
also hier bspw. `Ensemble_Senta`

2024-07-17 12:15 UTC, henrifnk commented on 01-variability.Rmd
> +SLP,Precip and TS. (@deser)
figure caption kann bspw. im chunk über fig.cap hinzugefügt werden (siehe markwodn doku)

2024-07-17 14:40 UTC, senntaa commented
Wieso funktioniert bei mir, dass mit diesem BookBib nicht? Lade mir eigentlich immer zuerst die neuste Version runter

2024-07-17 14:45 UTC, senntaa commented
![image](https://github.com/user-attachments/assets/bcbfe2b6-3c93-4351-84c7-000fa4f6a744)
Wenn ich das Bookbib im Master öffne kann ich meine Quellen auch schon finden

2024-07-18 08:04 UTC, henrifnk approved these changes
LGTM

2024-07-18 08:05 UTC, merged