09 epidemiologic
henrifnk/Seminar_ClimateNStatistics pull request #23
Opened 2024-07-18 12:08 UTC by OussamaMesbah

ran through without error on my side.

2024-07-18 13:51 UTC, henrifnk requested changes
Sieht schon gut und sauber aus, es fehlen aber noch einpaar kleine änderungen.
Mach dir vlt auch nochmal gedanken über die Referenzierrung.

2024-07-18 13:51 UTC, henrifnk commented on 09-epidemiologic.Rmd
> +---
Header und einführung bitte wie hier:
https://github.com/henrifnk/Seminar_ClimateNStatistics/blob/master/07-hydroLSTM.Rmd
Dann Caption so, wie im Bericht vorgesehen:
# Epidemiologic studies on the heat effects {#he2}
Un das noch dazu:
*Degree: Bachelor*

2024-07-18 13:51 UTC, henrifnk commented on 09-epidemiologic.Rmd
> +Compared to Zhao et al. (2021), Masselot et al. (2023) focuses on a more detailed regional scope by examining 854 cities in Europe, while Zhao's study covered 750 locations globally. Both studies cov
spätestens fhier fehlt die Korrekte referenzierung über @...

2024-07-18 13:51 UTC, henrifnk commented on 09-epidemiologic.Rmd
> +#### Masselot et al. (2023)
hier auch am besten nochmal referenzieren ;)

2024-07-18 15:49 UTC, OussamaMesbah reviewed
Header, introduction, and references fixed.

2024-07-19 07:18 UTC, henrifnk requested changes
Nur 1 kleinigkeit

2024-07-19 07:18 UTC, henrifnk commented on book.bib
> +@article{zhao2021global,
sorry für die kleinkarriertheit, aber hier und im nächsten bitte auch nur nachnamejahr nicht noch das erste wort oder so.
Danach ist es ready zum mergen :)

2024-07-19 07:54 UTC, OussamaMesbah commented on book.bib
> +@article{zhao2021global,
done :)

2024-07-19 07:55 UTC, henrifnk commented on book.bib
> +@article{zhao2021global,
top danke

2024-07-19 07:56 UTC, henrifnk approved these changes
LGTM

2024-07-19 09:44 UTC, merged